#!/bin/bash
# ==============================================================================
# Script Name: settings.sh
# Author: Plamen Milenkov
# Created: 2026-10-01
# Location: Sofia
# ==============================================================================
# Description:
# The names and folders used by the examples in this folder. It is sourced by
# every example, after the connection settings have been loaded.
#
# Notes:
# - Do not edit this file. To change a value, or to set the password, copy
#   settings.local.example.sh to settings.local.sh (git ignores it) and edit that.
# - Three accounts, all on this one server, so no other server is needed:
#     partner_to_pull_from  holds the sample files; the test account pulls them
#     the test account      pulls, routes and pushes: what is being measured
#     partner_to_push_to    receives what the test account pushes
#   Each account's billable count is then its own part of the story. See the
#   README.
# - Unlike Features/trigger-route-after-completed-pull, files here are NOT
#   renamed on receive or send. The point of this feature is telling billable
#   from non-billable transfers by their exact file names in File Tracking, so
#   the names stay exactly as given.
# ==============================================================================

# The test account. 00.run_all.sh and 99.cleanup_DELETE.sh take another name on
# the command line (BT_RUN_ACCOUNT, applied below, after settings.local.sh).
export BT_TEST_ACCOUNT="btTestAccount"
# The password of all three accounts
export BT_ACCOUNT_PASSWORD=""

# The two partner accounts. They are shared by every test account: each test
# account keeps its files in its own folder inside them, named after it.
export BT_PULL_PARTNER="partner_to_pull_from"
export BT_PUSH_PARTNER="partner_to_push_to"

# Each account's home folder is <BT_HOME_ROOT>/<account>. It must be a folder
# your server accepts; /home is the usual one.
export BT_HOME_ROOT="/home"

# How many files scenario 2.1 (inbound only) and scenario 2.2 (inbound, then one
# outbound) each run. 1 keeps the plain names only_inbound.txt and
# inbound_and_one_outbound.txt; more numbers them, only_inbound_1.txt and so on.
# 00.run_all.sh takes both on the command line (BT_RUN_INBOUND_ONLY and
# BT_RUN_IN_AND_OUT, applied below).
export BT_INBOUND_ONLY_COUNT="1"
export BT_IN_AND_OUT_COUNT="1"

# Folders are relative to an account's home: a login to this server, whether by
# a site, a subscription or the End User API, starts in the home folder. The
# test account's subscription folder holds one landing folder per scenario,
# s1 to s6. The partners' folders are set below, from the account name.
export BT_SUBSCRIPTION_FOLDER="/subscription"

# The partners are reached through this server's own SSH listener
export BT_SSH_HOST="${ST_SERVER}"
export BT_SSH_PORT="8022"

# The End User API, used to make the folders and put the sample files in place.
# It has its own port, and each account logs in as itself.
export BT_ENDUSER_PORT="8443"

# The file names the scenarios use, exactly as given, so they are easy to
# recognise in File Tracking by name alone
export BT_FILE_ONLY_INBOUND="only_inbound.txt"
export BT_FILE_ONE_OUTBOUND="inbound_and_one_outbound.txt"
export BT_FILE_TWO_OUTBOUNDS="inbound_and_two_outbounds.txt"
export BT_FILE_COMPRESS_1="file_1_for_compress.txt"
export BT_FILE_COMPRESS_2="file_2_for_compress.txt"
export BT_FILE_COMPRESSED_NAME="files_1_and_2_compressed.zip"
export BT_FILE_DECOMPRESS_1="file_1_inside_archive.txt"
export BT_FILE_DECOMPRESS_2="file_2_inside_archive.txt"
export BT_FILE_ARCHIVE_NAME="archive_with_2_files.zip"
export BT_FILE_DECOMPRESS2P_1="file_1_inside_archive_for_2_partners.txt"
export BT_FILE_DECOMPRESS2P_2="file_2_inside_archive_for_2_partners.txt"
export BT_FILE_ARCHIVE2P_NAME="archive_with_2_files_for_2_partners.zip"

# billable_GET_report: how many days back to report, today included
export BT_REPORT_DAYS="7"

# 00.run_all.sh pauses this long after triggering a pull, to let the pull, the
# route and the pushes run before the next step looks
export BT_STEP_PAUSE_SECONDS="5"
# How long files_GET_result.sh waits for the pushed files to arrive
export BT_WAIT_SECONDS="30"

# This feature's own directory, so the shared lib knows where to keep this
# feature's state (state.local.sh), separately from any other feature's.
export FEATURE_DIR="$(dirname "${BASH_SOURCE[0]}")"

LOCAL_SETTINGS="${FEATURE_DIR}/settings.local.sh"
if [ -f "${LOCAL_SETTINGS}" ]; then
    # shellcheck source=/dev/null
    source "${LOCAL_SETTINGS}"
fi

# Values given on the command line of 00.run_all.sh (or 99.cleanup_DELETE.sh)
# win over both the defaults above and settings.local.sh
[ -n "${BT_RUN_ACCOUNT}" ] && export BT_TEST_ACCOUNT="${BT_RUN_ACCOUNT}"
[ -n "${BT_RUN_INBOUND_ONLY}" ] && export BT_INBOUND_ONLY_COUNT="${BT_RUN_INBOUND_ONLY}"
[ -n "${BT_RUN_IN_AND_OUT}" ] && export BT_IN_AND_OUT_COUNT="${BT_RUN_IN_AND_OUT}"

# Everything below is derived from the account name, so two runs with different
# account names never collide on the server, and the cleanup of one never
# touches the other's objects
export BT_HOME_FOLDER="${BT_HOME_ROOT}/${BT_TEST_ACCOUNT}"
export BT_PULL_PARTNER_HOME="${BT_HOME_ROOT}/${BT_PULL_PARTNER}"
export BT_PUSH_PARTNER_HOME="${BT_HOME_ROOT}/${BT_PUSH_PARTNER}"
# This test account's own folder in each partner: the sample files wait in
# <it>/outbound-drop of partner_to_pull_from, and the pushes arrive in
# <it>/delivered-1 and <it>/delivered-2 of partner_to_push_to
export BT_RUN_FOLDER="/${BT_TEST_ACCOUNT}"
export BT_DROP_FOLDER="${BT_RUN_FOLDER}/outbound-drop"
export BT_DELIVERED_1_FOLDER="${BT_RUN_FOLDER}/delivered-1"
export BT_DELIVERED_2_FOLDER="${BT_RUN_FOLDER}/delivered-2"
export BT_PULL_SITE_PREFIX="${BT_TEST_ACCOUNT}PullSite"              # ...PullSite1 to 6
export BT_PUSH_SITE_1="${BT_TEST_ACCOUNT}PushSitePartner1"
export BT_PUSH_SITE_2="${BT_TEST_ACCOUNT}PushSitePartner2"
export BT_APPLICATION="${BT_TEST_ACCOUNT}Application"
export BT_TEMPLATE_ROUTE="${BT_TEST_ACCOUNT}PackageTemplate"
export BT_SIMPLE_ROUTE_PREFIX="${BT_TEST_ACCOUNT}SimpleRoute"        # ...SimpleRoute2 to 6
export BT_COMPOSITE_ROUTE_PREFIX="${BT_TEST_ACCOUNT}CompositeRoute"  # ...CompositeRoute2 to 6

source "${FEATURE_DIR}/../lib/post_admin.sh"

# enduser.sh is shared across Features/ and reads neutral names, not this
# feature's own BT_ prefix. It logs in as EU_ACCOUNT, read at login time.
export EU_ACCOUNT="${BT_TEST_ACCOUNT}"
export EU_ACCOUNT_PASSWORD="${BT_ACCOUNT_PASSWORD}"
export EU_ENDUSER_PORT="${BT_ENDUSER_PORT}"
source "${FEATURE_DIR}/../lib/enduser.sh"

# bt_login_as ACCOUNT: an End User API session as one of the three accounts
bt_login_as() {
    EU_ACCOUNT="$1"
    ar_enduser_login
}
