#!/bin/bash
# ==============================================================================
# Script Name: settings.sh
# Author: Plamen Milenkov
# Created: 2026-10-01
# Location: Sofia
# ==============================================================================
# Description:
# The names and folders used by the examples in this folder. It is sourced by
# every example, after the connection settings have been loaded.
#
# Notes:
# - Do not edit this file. To change a value, or to set the password, copy
#   settings.local.example.sh to settings.local.sh (git ignores it) and edit that.
# - The design is a loopback: the SecureTransport server is its own partner, for
#   the pull and for both of the two "remote partners" the pushes go to. No other
#   server is needed.
# - Unlike Features/trigger-route-after-completed-pull, files here are NOT
#   renamed on receive or send. The point of this feature is telling billable
#   from non-billable transfers by their exact file names in File Tracking, so
#   the names stay exactly as given.
# ==============================================================================

export BT_TEST_ACCOUNT="btTestAccount"
export BT_ACCOUNT_PASSWORD=""

# Must be a home folder your server accepts. /home/<name> is the usual one.
export BT_HOME_FOLDER="/home/${BT_TEST_ACCOUNT}"

# The folders below are relative to the account's home: a login to this server,
# whether by a site, a subscription or the End User API, starts in the home
# folder, so /outbound-drop means /home/btTestAccount/outbound-drop.
export BT_DROP_FOLDER="/outbound-drop"
export BT_DELIVERED_1_FOLDER="/delivered-1"
export BT_DELIVERED_2_FOLDER="/delivered-2"
# One subscription landing folder per scenario, named s1 to s6
export BT_SUBSCRIPTION_FOLDER="/subscription"

# The loopback partner: this server's own SSH listener
export BT_SSH_HOST="${ST_SERVER}"
export BT_SSH_PORT="8022"

# The End User API, used to put the sample files and archives in place. It has
# its own port, and the account logs in as itself.
export BT_ENDUSER_PORT="8443"

# The names of the objects the examples create
export BT_PULL_SITE_PREFIX="btPullSite"      # btPullSite1 .. btPullSite6
export BT_PUSH_SITE_1="btPushSitePartner1"
export BT_PUSH_SITE_2="btPushSitePartner2"
export BT_APPLICATION="btTransferApplication"
export BT_TEMPLATE_ROUTE="btPackageTemplate"
export BT_SIMPLE_ROUTE_PREFIX="btSimpleRoute"      # btSimpleRoute2 .. btSimpleRoute6
export BT_COMPOSITE_ROUTE_PREFIX="btCompositeRoute" # btCompositeRoute2 .. btCompositeRoute6

# The file names the scenarios use, exactly as given, so they are easy to
# recognise in File Tracking by name alone
export BT_FILE_ONLY_INBOUND="only_inbound.txt"
export BT_FILE_ONE_OUTBOUND="inbound_and_one_outbound.txt"
export BT_FILE_TWO_OUTBOUNDS="inbound_and_two_outbounds.txt"
export BT_FILE_COMPRESS_1="file_1_for_compress.txt"
export BT_FILE_COMPRESS_2="file_2_for_compress.txt"
export BT_FILE_COMPRESSED_NAME="files_1_and_2_compressed.zip"
export BT_FILE_DECOMPRESS_1="file_1_inside_archive.txt"
export BT_FILE_DECOMPRESS_2="file_2_inside_archive.txt"
export BT_FILE_ARCHIVE_NAME="archive_with_2_files.zip"
export BT_FILE_DECOMPRESS2P_1="file_1_inside_archive_for_2_partners.txt"
export BT_FILE_DECOMPRESS2P_2="file_2_inside_archive_for_2_partners.txt"
export BT_FILE_ARCHIVE2P_NAME="archive_with_2_files_for_2_partners.zip"

# Step billable_GET_report: how many days back to report, today included, and
# the account the report is scoped to
export BT_REPORT_DAYS="7"

# 00.run_all.sh pauses this long after triggering a pull, to let the pull, the
# route and the pushes run before the next step looks
export BT_STEP_PAUSE_SECONDS="5"
# How long files_GET_result.sh waits for the pushed files to arrive
export BT_WAIT_SECONDS="30"

# This feature's own directory, so the shared lib knows where to keep this
# feature's state (state.local.sh), separately from any other feature's.
export FEATURE_DIR="$(dirname "${BASH_SOURCE[0]}")"

LOCAL_SETTINGS="${FEATURE_DIR}/settings.local.sh"
if [ -f "${LOCAL_SETTINGS}" ]; then
    # shellcheck source=/dev/null
    source "${LOCAL_SETTINGS}"
fi

source "${FEATURE_DIR}/../lib/post_admin.sh"

# enduser.sh is shared across Features/ and reads neutral names, not this
# feature's own BT_ prefix
export EU_ACCOUNT="${BT_TEST_ACCOUNT}"
export EU_ACCOUNT_PASSWORD="${BT_ACCOUNT_PASSWORD}"
export EU_ENDUSER_PORT="${BT_ENDUSER_PORT}"
source "${FEATURE_DIR}/../lib/enduser.sh"
