@echo off
REM ==============================================================================
REM Script Name: settings.bat
REM Author: Plamen Milenkov
REM Created: 2026-10-01
REM Location: Sofia
REM ==============================================================================
REM Description:
REM The names and folders used by the examples in this folder. It is called by
REM every example, after the connection settings have been loaded.
REM
REM Notes:
REM - Do not edit this file. To change a value, or to set the password, copy
REM   settings.local.example.bat to settings.local.bat (git ignores it) and edit
REM   that.
REM - Three accounts, all on this one server, so no other server is needed:
REM     partner_to_pull_from  holds the sample files; the test account pulls them
REM     the test account      pulls, routes and pushes: what is being measured
REM     partner_to_push_to    receives what the test account pushes
REM   Each account's billable count is then its own part of the story. See the
REM   README.
REM - Unlike Features/trigger-route-after-completed-pull, files here are NOT
REM   renamed on receive or send. The point of this feature is telling billable
REM   from non-billable transfers by their exact file names in File Tracking, so
REM   the names stay exactly as given.
REM ==============================================================================

REM The test account. 00.run_all.bat and 99.cleanup_DELETE.bat take another name
REM on the command line (BT_RUN_ACCOUNT, applied below, after settings.local.bat).
SET BT_TEST_ACCOUNT=btTestAccount
REM The password of all three accounts
SET BT_ACCOUNT_PASSWORD=

REM The two partner accounts. They are shared by every test account: each test
REM account keeps its files in its own folder inside them, named after it.
SET BT_PULL_PARTNER=partner_to_pull_from
SET BT_PUSH_PARTNER=partner_to_push_to

REM Each account's home folder is <BT_HOME_ROOT>/<account>. It must be a folder
REM your server accepts; /home is the usual one.
SET BT_HOME_ROOT=/home

REM How many files scenario 2.1 (inbound only) and scenario 2.2 (inbound, then one
REM outbound) each run. 1 keeps the plain names only_inbound.txt and
REM inbound_and_one_outbound.txt; more numbers them, only_inbound_1.txt and so on.
REM 00.run_all.bat takes both on the command line (BT_RUN_INBOUND_ONLY and
REM BT_RUN_IN_AND_OUT, applied below).
SET BT_INBOUND_ONLY_COUNT=1
SET BT_IN_AND_OUT_COUNT=1

REM Folders are relative to an account's home: a login to this server, whether by
REM a site, a subscription or the End User API, starts in the home folder. The
REM test account's subscription folder holds one landing folder per scenario,
REM s1 to s6. The partners' folders are set below, from the account name.
SET BT_SUBSCRIPTION_FOLDER=/subscription

REM The partners are reached through this server's own SSH listener
SET BT_SSH_HOST=%ST_SERVER%
SET BT_SSH_PORT=8022

REM The End User API, used to make the folders and put the sample files in place.
REM It has its own port, and each account logs in as itself.
SET BT_ENDUSER_PORT=8443

REM The file names the scenarios use, exactly as given, so they are easy to
REM recognise in File Tracking by name alone
SET BT_FILE_ONLY_INBOUND=only_inbound.txt
SET BT_FILE_ONE_OUTBOUND=inbound_and_one_outbound.txt
SET BT_FILE_TWO_OUTBOUNDS=inbound_and_two_outbounds.txt
SET BT_FILE_COMPRESS_1=file_1_for_compress.txt
SET BT_FILE_COMPRESS_2=file_2_for_compress.txt
SET BT_FILE_COMPRESSED_NAME=files_1_and_2_compressed.zip
SET BT_FILE_DECOMPRESS_1=file_1_inside_archive.txt
SET BT_FILE_DECOMPRESS_2=file_2_inside_archive.txt
SET BT_FILE_ARCHIVE_NAME=archive_with_2_files.zip
SET BT_FILE_DECOMPRESS2P_1=file_1_inside_archive_for_2_partners.txt
SET BT_FILE_DECOMPRESS2P_2=file_2_inside_archive_for_2_partners.txt
SET BT_FILE_ARCHIVE2P_NAME=archive_with_2_files_for_2_partners.zip

REM billable_GET_report: how many days back to report, today included
SET BT_REPORT_DAYS=7

REM 00.run_all.bat pauses this long after triggering a pull, to let the pull, the
REM route and the pushes run before the next step looks
SET BT_STEP_PAUSE_SECONDS=5
REM How long files_GET_result.bat waits for the pushed files to arrive
SET BT_WAIT_SECONDS=30

REM This feature's own directory, so the shared lib knows where to keep this
REM feature's state (state.local.bat), separately from any other feature's.
SET FEATURE_DIR=%~dp0

IF EXIST "%~dp0settings.local.bat" CALL "%~dp0settings.local.bat"

REM Values given on the command line of 00.run_all.bat (or 99.cleanup_DELETE.bat)
REM win over both the defaults above and settings.local.bat
IF DEFINED BT_RUN_ACCOUNT SET BT_TEST_ACCOUNT=%BT_RUN_ACCOUNT%
IF DEFINED BT_RUN_INBOUND_ONLY SET BT_INBOUND_ONLY_COUNT=%BT_RUN_INBOUND_ONLY%
IF DEFINED BT_RUN_IN_AND_OUT SET BT_IN_AND_OUT_COUNT=%BT_RUN_IN_AND_OUT%

REM Everything below is derived from the account name, so two runs with different
REM account names never collide on the server, and the cleanup of one never
REM touches the other's objects
SET BT_HOME_FOLDER=%BT_HOME_ROOT%/%BT_TEST_ACCOUNT%
SET BT_PULL_PARTNER_HOME=%BT_HOME_ROOT%/%BT_PULL_PARTNER%
SET BT_PUSH_PARTNER_HOME=%BT_HOME_ROOT%/%BT_PUSH_PARTNER%
REM This test account's own folder in each partner: the sample files wait in
REM <it>/outbound-drop of partner_to_pull_from, and the pushes arrive in
REM <it>/delivered-1 and <it>/delivered-2 of partner_to_push_to
SET BT_RUN_FOLDER=/%BT_TEST_ACCOUNT%
SET BT_DROP_FOLDER=%BT_RUN_FOLDER%/outbound-drop
SET BT_DELIVERED_1_FOLDER=%BT_RUN_FOLDER%/delivered-1
SET BT_DELIVERED_2_FOLDER=%BT_RUN_FOLDER%/delivered-2
SET BT_PULL_SITE_PREFIX=%BT_TEST_ACCOUNT%PullSite
SET BT_PUSH_SITE_1=%BT_TEST_ACCOUNT%PushSitePartner1
SET BT_PUSH_SITE_2=%BT_TEST_ACCOUNT%PushSitePartner2
SET BT_APPLICATION=%BT_TEST_ACCOUNT%Application
SET BT_TEMPLATE_ROUTE=%BT_TEST_ACCOUNT%PackageTemplate
SET BT_SIMPLE_ROUTE_PREFIX=%BT_TEST_ACCOUNT%SimpleRoute
SET BT_COMPOSITE_ROUTE_PREFIX=%BT_TEST_ACCOUNT%CompositeRoute
REM Ids saved by earlier examples
IF EXIST "%~dp0state.local.bat" CALL "%~dp0state.local.bat"

REM enduser.bat is shared across Features/ and reads neutral names, not this
REM feature's own BT_ prefix. It logs in as EU_ACCOUNT, read at login time: to
REM log in as a partner, SET EU_ACCOUNT first.
SET EU_ACCOUNT=%BT_TEST_ACCOUNT%
SET EU_ACCOUNT_PASSWORD=%BT_ACCOUNT_PASSWORD%
SET EU_ENDUSER_PORT=%BT_ENDUSER_PORT%
