@echo off
REM ==============================================================================
REM Script Name: settings.bat
REM Author: Plamen Milenkov
REM Created: 2026-10-01
REM Location: Sofia
REM ==============================================================================
REM Description:
REM The names and folders used by the examples in this folder. It is called by
REM every example, after the connection settings have been loaded.
REM
REM Notes:
REM - Do not edit this file. To change a value, or to set the password, copy
REM   settings.local.example.bat to settings.local.bat (git ignores it) and edit
REM   that.
REM - The design is a loopback: the SecureTransport server is its own partner, for
REM   the pull and for both of the two "remote partners" the pushes go to. No other
REM   server is needed.
REM - Unlike Features/trigger-route-after-completed-pull, files here are NOT
REM   renamed on receive or send. The point of this feature is telling billable
REM   from non-billable transfers by their exact file names in File Tracking, so
REM   the names stay exactly as given.
REM ==============================================================================

SET BT_TEST_ACCOUNT=btTestAccount
SET BT_ACCOUNT_PASSWORD=

REM Must be a home folder your server accepts. /home/<name> is the usual one.
SET BT_HOME_FOLDER=/home/%BT_TEST_ACCOUNT%

REM The folders below are relative to the account's home: a login to this server,
REM whether by a site, a subscription or the End User API, starts in the home
REM folder, so /outbound-drop means /home/btTestAccount/outbound-drop.
SET BT_DROP_FOLDER=/outbound-drop
SET BT_DELIVERED_1_FOLDER=/delivered-1
SET BT_DELIVERED_2_FOLDER=/delivered-2
REM One subscription landing folder per scenario, named s1 to s6
SET BT_SUBSCRIPTION_FOLDER=/subscription

REM The loopback partner: this server's own SSH listener
SET BT_SSH_HOST=%ST_SERVER%
SET BT_SSH_PORT=8022

REM The End User API, used to put the sample files and archives in place. It has
REM its own port, and the account logs in as itself.
SET BT_ENDUSER_PORT=8443

REM The names of the objects the examples create
SET BT_PULL_SITE_PREFIX=btPullSite
SET BT_PUSH_SITE_1=btPushSitePartner1
SET BT_PUSH_SITE_2=btPushSitePartner2
SET BT_APPLICATION=btTransferApplication
SET BT_TEMPLATE_ROUTE=btPackageTemplate
SET BT_SIMPLE_ROUTE_PREFIX=btSimpleRoute
SET BT_COMPOSITE_ROUTE_PREFIX=btCompositeRoute

REM The file names the scenarios use, exactly as given, so they are easy to
REM recognise in File Tracking by name alone
SET BT_FILE_ONLY_INBOUND=only_inbound.txt
SET BT_FILE_ONE_OUTBOUND=inbound_and_one_outbound.txt
SET BT_FILE_TWO_OUTBOUNDS=inbound_and_two_outbounds.txt
SET BT_FILE_COMPRESS_1=file_1_for_compress.txt
SET BT_FILE_COMPRESS_2=file_2_for_compress.txt
SET BT_FILE_COMPRESSED_NAME=files_1_and_2_compressed.zip
SET BT_FILE_DECOMPRESS_1=file_1_inside_archive.txt
SET BT_FILE_DECOMPRESS_2=file_2_inside_archive.txt
SET BT_FILE_ARCHIVE_NAME=archive_with_2_files.zip
SET BT_FILE_DECOMPRESS2P_1=file_1_inside_archive_for_2_partners.txt
SET BT_FILE_DECOMPRESS2P_2=file_2_inside_archive_for_2_partners.txt
SET BT_FILE_ARCHIVE2P_NAME=archive_with_2_files_for_2_partners.zip

REM Step billable_GET_report: how many days back to report, today included, and
REM the account the report is scoped to
SET BT_REPORT_DAYS=7

REM 00.run_all.bat pauses this long after triggering a pull, to let the pull, the
REM route and the pushes run before the next step looks
SET BT_STEP_PAUSE_SECONDS=5
REM How long files_GET_result.bat waits for the pushed files to arrive
SET BT_WAIT_SECONDS=30

REM This feature's own directory, so the shared lib knows where to keep this
REM feature's state (state.local.bat), separately from any other feature's.
SET FEATURE_DIR=%~dp0

IF EXIST "%~dp0settings.local.bat" CALL "%~dp0settings.local.bat"
REM Ids saved by earlier examples
IF EXIST "%~dp0state.local.bat" CALL "%~dp0state.local.bat"

REM enduser.bat is shared across Features/ and reads neutral names, not this
REM feature's own BT_ prefix
SET EU_ACCOUNT=%BT_TEST_ACCOUNT%
SET EU_ACCOUNT_PASSWORD=%BT_ACCOUNT_PASSWORD%
SET EU_ENDUSER_PORT=%BT_ENDUSER_PORT%
