@echo off
REM ==============================================================================
REM Script Name: settings.bat
REM Author: Plamen Milenkov
REM Created: 2026-10-01
REM Location: Sofia
REM ==============================================================================
REM Description:
REM The names and folders used by the examples in this folder. It is called by
REM every example, after the connection settings have been loaded.
REM
REM Notes:
REM - Do not edit this file. To change a value, or to set the password, copy
REM   settings.local.example.bat to settings.local.bat (git ignores it) and edit
REM   that.
REM - The design is a loopback: the SecureTransport server is its own partner for
REM   both the pull and the push, so no other server is needed.
REM - delivered must not be the subscription folder. If it were, the pushed files
REM   would be seen as new arrivals and the route would trigger itself forever.
REM ==============================================================================

SET AR_TEST_ACCOUNT=arTestAccount
SET AR_ACCOUNT_PASSWORD=

SET AR_PULL_SITE=arTestPullSite
SET AR_PUSH_SITE=arTestPushSite

REM The loopback partner: this server's own SSH listener
SET AR_SSH_HOST=%ST_SERVER%
SET AR_SSH_PORT=8022

REM The End User API, used to put the sample files in place. It has its own port
REM and the account logs in as itself.
SET AR_ENDUSER_PORT=8443
REM The folder as the account sees it, from its home folder
SET AR_UPLOAD_FOLDER=/outbound-drop
SET AR_SAMPLE_FILES=3
REM pull_test_1.txt, pull_test_2.txt, ...
SET AR_SAMPLE_PREFIX=pull_test_

REM One account does the pull and the push, so File Tracking shows each file several
REM times. Renaming at each leg tells the rows apart: the pull site renames files as
REM they arrive (doAsIn), the push site renames them as they leave (doAsOut). A
REM pulled file is pull_test_1.txt_PULLED, and after the push pull_test_1.txt_PULLED_PUSHED.
SET AR_PULLED_SUFFIX=_PULLED
SET AR_PUSHED_SUFFIX=_PUSHED
SET AR_PULL_RENAME=${stenv.target}%AR_PULLED_SUFFIX%
SET AR_PUSH_RENAME=${stenv.target}%AR_PUSHED_SUFFIX%
REM The names of what steps 6 to 10 create
SET AR_APPLICATION=arTestPullApplication
SET AR_TEMPLATE_ROUTE=arTestPackageTemplate
SET AR_SIMPLE_ROUTE=arTestSendToPushSite
SET AR_COMPOSITE_ROUTE=arTestPullPackage

REM The trigger file. The pattern is written once, here; SecureTransport evaluates
REM the ${date(...)} expression itself, once per pull, when it creates the file.
REM The condition must match whatever name results, so both come from this block.
REM Day before month (the EMEA order)
SET AR_TRIGGER_DATE_PATTERN=yyyyddMMHHmmss
SET AR_TRIGGER_FILE_NAME=file_${date('%AR_TRIGGER_DATE_PATTERN%')}.trigger
REM Two backslashes, as SecureTransport's expression language wants in a string
SET AR_TRIGGER_CONDITION=${stenv['target'].matches('.*\\.trigger')?1:0}

REM Step 13: the folders to show, as the account sees them, and how long to wait
REM for the last one to fill up
SET AR_CHECK_FOLDERS=outbound-drop subscription delivered
SET AR_WAIT_SECONDS=30
REM 00.run_all.bat pauses this long after steps 11 and 12, to let the pull and the route run
SET AR_STEP_PAUSE_SECONDS=5
REM The folders to create in the account's home, as the account sees them
SET AR_CREATE_FOLDERS=outbound-drop delivered
REM What step 99 empties and removes from the home folder: the two folders step 4 made,
REM and the subscription folder, whose pulled files and trigger files would otherwise
REM be picked up by the next run.
SET AR_CLEAN_FOLDERS=%AR_CREATE_FOLDERS% subscription

REM Must be a home folder your server accepts. /home/<name> is the usual one.
SET AR_HOME_FOLDER=/home/%AR_TEST_ACCOUNT%
REM The folders below are relative to the account's home. A login to this server,
REM whether by the loopback sites, the subscription or the End User API, starts in
REM the home folder, so /outbound-drop means /home/arTestAccount/outbound-drop.
SET AR_PULL_FROM_FOLDER=/outbound-drop
SET AR_SUBSCRIPTION_FOLDER=/subscription
SET AR_DELIVERED_FOLDER=/delivered

REM This feature's own directory, so the shared lib knows where to keep this
REM feature's state (state.local.bat), separately from any other feature's.
SET FEATURE_DIR=%~dp0

IF EXIST "%~dp0settings.local.bat" CALL "%~dp0settings.local.bat"
REM Ids saved by earlier examples
IF EXIST "%~dp0state.local.bat" CALL "%~dp0state.local.bat"

REM enduser.bat is shared across Features/ and reads neutral names, not this
REM feature's own AR_ prefix
SET EU_ACCOUNT=%AR_TEST_ACCOUNT%
SET EU_ACCOUNT_PASSWORD=%AR_ACCOUNT_PASSWORD%
SET EU_ENDUSER_PORT=%AR_ENDUSER_PORT%
