#!/bin/bash
# ==============================================================================
# Script Name: settings.sh
# Author: Plamen Milenkov
# Created: 2026-10-01
# Location: Sofia
# ==============================================================================
# Description:
# The names and folders used by the examples in this folder. It is sourced by
# every example, after the connection settings have been loaded.
#
# Notes:
# - Do not edit this file. To change a value, or to set the password, copy
#   settings.local.example.sh to settings.local.sh (git ignores it) and edit that.
# - The design is a loopback: the SecureTransport server is its own partner for
#   both the pull and the push, so no other server is needed.
# - delivered must not be the subscription folder. If it were, the pushed files
#   would be seen as new arrivals and the route would trigger itself forever.
# ==============================================================================

export AR_TEST_ACCOUNT="arTestAccount"
export AR_ACCOUNT_PASSWORD=""

export AR_PULL_SITE="arTestPullSite"
export AR_PUSH_SITE="arTestPushSite"

# The loopback partner: this server's own SSH listener
export AR_SSH_HOST="${ST_SERVER}"
export AR_SSH_PORT="8022"

# The End User API, used to put the sample files in place. It has its own port
# and the account logs in as itself.
export AR_ENDUSER_PORT="8443"
export AR_UPLOAD_FOLDER="/outbound-drop"   # the same folder, for the sample files
export AR_SAMPLE_FILES="3"
export AR_SAMPLE_PREFIX="pull_test_"     # pull_test_1.txt, pull_test_2.txt, ...

# One account does the pull and the push, so File Tracking shows each file several
# times. Renaming at each leg tells the rows apart: the pull site renames files as
# they arrive (doAsIn), the push site renames them as they leave (doAsOut). A
# pulled file is pull_test_1.txt_PULLED, and after the push pull_test_1.txt_PULLED_PUSHED.
export AR_PULLED_SUFFIX="_PULLED"
export AR_PUSHED_SUFFIX="_PUSHED"
export AR_PULL_RENAME="\${stenv.target}${AR_PULLED_SUFFIX}"
export AR_PUSH_RENAME="\${stenv.target}${AR_PUSHED_SUFFIX}"
# The names of what steps 6 to 10 create
export AR_APPLICATION="arTestPullApplication"
export AR_TEMPLATE_ROUTE="arTestPackageTemplate"
export AR_SIMPLE_ROUTE="arTestSendToPushSite"
export AR_COMPOSITE_ROUTE="arTestPullPackage"

# The trigger file. The pattern is written once, here; SecureTransport evaluates
# the ${date(...)} expression itself, once per pull, when it creates the file.
# The condition must match whatever name results, so both come from this block.
# Day before month (the EMEA order)
export AR_TRIGGER_DATE_PATTERN="yyyyddMMHHmmss"
export AR_TRIGGER_FILE_NAME="file_\${date('${AR_TRIGGER_DATE_PATTERN}')}.trigger"
# Two backslashes, as SecureTransport's expression language wants in a string
export AR_TRIGGER_CONDITION="\${stenv['target'].matches('.*\\\\.trigger')?1:0}"

# The folders to create in the account's home, as the account sees them
# Step 13: the folders to show, as the account sees them, and how long to wait
# for the last one to fill up
export AR_CHECK_FOLDERS="outbound-drop subscription delivered"
export AR_WAIT_SECONDS="30"
# 00.run_all.sh pauses this long after steps 11 and 12, to let the pull and the route run
export AR_STEP_PAUSE_SECONDS="5"
export AR_CREATE_FOLDERS="outbound-drop delivered"
# What step 99 empties and removes from the home folder: the two folders step 4 made,
# and the subscription folder, whose pulled files and trigger files would otherwise
# be picked up by the next run.
export AR_CLEAN_FOLDERS="${AR_CREATE_FOLDERS} subscription"

# Must be a home folder your server accepts. /home/<name> is the usual one.
export AR_HOME_FOLDER="/home/${AR_TEST_ACCOUNT}"
# The folders below are relative to the account's home. A login to this server,
# whether by the loopback sites, the subscription or the End User API, starts in
# the home folder, so /outbound-drop means /home/arTestAccount/outbound-drop.
export AR_PULL_FROM_FOLDER="/outbound-drop"
export AR_SUBSCRIPTION_FOLDER="/subscription"
export AR_DELIVERED_FOLDER="/delivered"

LOCAL_SETTINGS="$(dirname "${BASH_SOURCE[0]}")/settings.local.sh"
if [ -f "${LOCAL_SETTINGS}" ]; then
    # shellcheck source=/dev/null
    source "${LOCAL_SETTINGS}"
fi

source "$(dirname "${BASH_SOURCE[0]}")/post_admin.sh"
source "$(dirname "${BASH_SOURCE[0]}")/enduser.sh"
