#!/bin/bash
# ==============================================================================
# Script Name: settings.sh
# Author: Plamen Milenkov
# Created: 2026-10-01
# Location: Sofia
# ==============================================================================
# Description:
# The names and folders used by the examples in this folder. It is sourced by
# every example, after the connection settings have been loaded.
#
# Notes:
# - Do not edit this file. To change a value, or to set the password, copy
#   settings.local.example.sh to settings.local.sh (git ignores it) and edit that.
# - The design is a loopback: the SecureTransport server is its own partner for
#   both the pull and the push, so no other server is needed.
# - delivered must not be the subscription folder. If it were, the pushed files
#   would be seen as new arrivals and the route would trigger itself forever.
# - The account's name is read under three names, all the same account:
#   AR_RUN_ACCOUNT (what 00.run_all.sh or 99.cleanup_DELETE.sh was given on the
#   command line: it wins), AR_TEST_ACCOUNT (what the examples use) and EU_ACCOUNT
#   (what the shared End User helper logs in as). The password is likewise
#   AR_ACCOUNT_PASSWORD here and EU_ACCOUNT_PASSWORD in the helper. Features/lib
#   uses its own names (ar_*, AR_STATE_FILE, AR_EU_*, EU_*): they are not settings.
# ==============================================================================

# The test account. 00.run_all.sh and 99.cleanup_DELETE.sh take another name on the
# command line (AR_RUN_ACCOUNT, applied below, after settings.local.sh).
# When nobody chose a name, 00.run_all.sh may move to <default>_2, _3 and so on:
# see "A stale home folder" in its notes.
export AR_DEFAULT_ACCOUNT="arTestAccount"
export AR_TEST_ACCOUNT="${AR_DEFAULT_ACCOUNT}"
export AR_ACCOUNT_PASSWORD=""

export AR_PULL_SITE="arTestPullSite"
export AR_PUSH_SITE="arTestPushSite"

# The loopback partner: this server's own SSH listener
export AR_SSH_HOST="${ST_SERVER}"
export AR_SSH_PORT="8022"

# The End User API, used to put the sample files in place. It has its own port
# and the account logs in as itself.
export AR_ENDUSER_PORT="8443"
export AR_UPLOAD_FOLDER="/outbound-drop"   # the same folder, for the sample files
export AR_SAMPLE_FILES="3"
export AR_SAMPLE_PREFIX="pull_test_"     # pull_test_1.txt, pull_test_2.txt, ...

# One account does the pull and the push, so File Tracking shows each file several
# times. Renaming at each leg tells the rows apart: the pull site renames files as
# they arrive (doAsIn), the push site renames them as they leave (doAsOut). A
# pulled file is pull_test_1.txt_PULLED, and after the push pull_test_1.txt_PULLED_PUSHED.
export AR_PULLED_SUFFIX="_PULLED"
export AR_PUSHED_SUFFIX="_PUSHED"
export AR_PULL_RENAME="\${stenv.target}${AR_PULLED_SUFFIX}"
export AR_PUSH_RENAME="\${stenv.target}${AR_PUSHED_SUFFIX}"
# The names of what steps 6 to 10 create
export AR_APPLICATION="arTestPullApplication"
export AR_TEMPLATE_ROUTE="arTestPackageTemplate"
export AR_SIMPLE_ROUTE="arTestSendToPushSite"
export AR_COMPOSITE_ROUTE="arTestPullPackage"

# The trigger file. The pattern is written once, here; SecureTransport evaluates
# the ${date(...)} expression itself, once per pull, when it creates the file.
# The condition must match whatever name results, so both come from this block.
# Day before month (the EMEA order)
export AR_TRIGGER_DATE_PATTERN="yyyyddMMHHmmss"
export AR_TRIGGER_FILE_NAME="file_\${date('${AR_TRIGGER_DATE_PATTERN}')}.trigger"
# Two backslashes, as SecureTransport's expression language wants in a string
export AR_TRIGGER_CONDITION="\${stenv['target'].matches('.*\\\\.trigger')?1:0}"

# The folders to create in the account's home, as the account sees them
# Step 13: the folders to show, as the account sees them, and how long to wait
# for the last one to fill up
export AR_CHECK_FOLDERS="outbound-drop subscription delivered"
export AR_WAIT_SECONDS="30"
# 00.run_all.sh pauses this long after steps 11 and 12, to let the pull and the route run
export AR_STEP_PAUSE_SECONDS="5"
export AR_CREATE_FOLDERS="outbound-drop delivered"
# What step 99 empties and removes from the home folder: the two folders step 4 made,
# and the subscription folder, whose pulled files and trigger files would otherwise
# be picked up by the next run.
export AR_CLEAN_FOLDERS="${AR_CREATE_FOLDERS} subscription"

# The account's home folder is <AR_HOME_ROOT>/<account>, set below, after the
# account name is known. It must be a folder your server accepts; /home is the
# usual one.
export AR_HOME_ROOT="/home"
# The folders below are relative to the account's home. A login to this server,
# whether by the loopback sites, the subscription or the End User API, starts in
# the home folder, so /outbound-drop means /home/arTestAccount/outbound-drop.
export AR_PULL_FROM_FOLDER="/outbound-drop"
export AR_SUBSCRIPTION_FOLDER="/subscription"
export AR_DELIVERED_FOLDER="/delivered"

# This feature's own directory, so the shared lib knows where to keep this
# feature's state (state.local.sh), separately from any other feature's.
export FEATURE_DIR="$(dirname "${BASH_SOURCE[0]}")"

LOCAL_SETTINGS="${FEATURE_DIR}/settings.local.sh"
if [ -f "${LOCAL_SETTINGS}" ]; then
    # shellcheck source=/dev/null
    source "${LOCAL_SETTINGS}"
fi

# A value given on the command line of 00.run_all.sh (or 99.cleanup_DELETE.sh) wins
# over both the default above and settings.local.sh
[ -n "${AR_RUN_ACCOUNT}" ] && export AR_TEST_ACCOUNT="${AR_RUN_ACCOUNT}"

# Derived from the account name
export AR_HOME_FOLDER="${AR_HOME_ROOT}/${AR_TEST_ACCOUNT}"

source "${FEATURE_DIR}/../lib/post_admin.sh"
source "${FEATURE_DIR}/../lib/admin_calls.sh"

# enduser.sh is shared across Features/ and reads neutral names, not this
# feature's own AR_ prefix
export EU_ACCOUNT="${AR_TEST_ACCOUNT}"
export EU_ACCOUNT_PASSWORD="${AR_ACCOUNT_PASSWORD}"
export EU_ENDUSER_PORT="${AR_ENDUSER_PORT}"
source "${FEATURE_DIR}/../lib/enduser.sh"
source "${FEATURE_DIR}/../lib/home_folder.sh"
